@startuml "WeaMyL Context"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
 
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
 
LAYOUT_WITH_LEGEND()
 
Person(user_R, "Researcher" , "Climate researcher - not working on developing ML models, just evaluating the results", "?")
 
Person(user_SA, "SysAdmin", "tja", "?")
 
Person(user_F, "Forecaster", "tja", "?")
 
System(WeaMyL,"Software system","The system will use Machine Learning algorithms to predict severe weather conditions in near future(nowcast) from satellite and radar observations")
 
System(Thredds_rad,"Software system", "Met Norway's Data distribution service for Satellite data","EUMETSAT")
 
System(Thredds_sat,"Software system",  "Met Norway's Data distribution service for Radar data")
 
System(nws,"National warning  system", "The forecasters forecast working desktop tool")
 
System(Mltp,"Training platform ", "The platform for developing ML algorithms and facilities for training")
 
 
@enduml
