@startuml "WeaMyL Container"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
 
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
 

LAYOUT_WITH_LEGEND()

Person(user_R, "Researcher" , "Studying severe weather episodes and data dissemination", "User")
 
Person(user_SA, "SysAdmin", "Responsible for the configuration and the maintenance runtime and build environment ", "User")
 
Person(user_F, "Operational Meteorologist", "Responsible for issuing severe weather warning", "User")
 
'System(WeaMyL,"WeaMyL","The system will use Machine Learning algorithms to predict severe weather conditions in near future(nowcast) from satellite and radar observations")
 
System_Boundary(WeaMyL, "WeaMyL"){
    Container(ML_Motor,"Machine learning motor","?")
    Container(Forecaster_Backend,"GeoWeb_DataService","C","Draw polygons from indicated areas from the MachineLearning output" )
    Container(GeoWeb,"GeoWeb","JavaScript,Angular","Visualizing WeaMyL-output in maps")
    ContainerDb(Atlas,"Annotated Atlas","Semantic database,Go","Metadatacatalog API with reference to annotated meteorologigcal data")
    Container(Data_Aq,"Data acquisition", "ECMWF SAPP Module?","Collecting data from predefined sources")
    
}

System_Ext(Thredds,"Thredds", "Met Norway's Data distribution service for Radar and Satellite data","EUMETSAT")
System_Ext(DS,"Radar and satelite?", "ANM's Data distribution service for Radar and Satellite data","EUMETSAT")

 
System_Ext(nws,"National warning  system", "The forecasters forecast working desktop tool")
 
System_Ext(Mltp,"Training platform ", "The platform for developing ML algorithms and facilities for training")
System_Ext(MetObs,"Observations(Frost)", "Norwegian observations")
System_Ext(AnmObs,"Observations(ANM) ", "Romanian observation")
System_Ext(ANM_light,"Ligthning data Romania")
System_Ext(MET_light,"Ligthning data Norway","api.met.no?")

Rel_R(ML_Motor,Forecaster_Backend,"Getting weather predictions","?")
Rel_R(Forecaster_Backend,GeoWeb,"MapLayers", "wms and text")

Rel_U(Data_Aq,ML_Motor,"getting input parameters","Format?")
Rel_U(Atlas,GeoWeb,"Store metadata about severe weather")

Rel_D(user_F,GeoWeb,"Checking the severe weather warning proposal")
Rel_R(user_R,Atlas,"Getting interesting stuff from the Anotation atlas")
Rel_R(user_R,Mltp,"Training the machinlearning algorithm")
Rel_D(user_F,Forecaster_Backend,"Editing threashold values")
Rel_D(user_SA,WeaMyL,"Maintain build and configs")

Rel_U(Thredds,Data_Aq,"Getting radar and satellite data","NetCDF")


Rel_R(GeoWeb,nws,"Send out warningmessage","Format?")
'Rel_U(Mltp,ML_Motor,"Deploying ML algorithm")
'Rel_U(ANM_light,Data_Aq,"Fetching lighting observation, format??")
'Rel_U(MET_light,Data_Aq,"Fetching lighting observation, format??")
'Rel_U(MetObs,Data_Aq,"Fetching regular observations, Rest API, formats? GeoJson")
'Rel_U(AnmObs,Data_Aq,"Fetching regular observation, ??")
 
'

 

 
@enduml
