@startuml "WeaMyL Container"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
 
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
 
LAYOUT_WITH_LEGEND()
 
Person(user_R, "Researcher" , "Climate researcher - not working on developing ML models, just evaluating the results", "User")
 
Person(user_SA, "SysAdmin", "tja", "User")
 
Person(user_F, "Forecaster", "Responsible for the daily forecast and to send out warning messages", "User")
 
'System(WeaMyL,"WeaMyL","The system will use Machine Learning algorithms to predict severe weather conditions in near future(nowcast) from satellite and radar observations")
 

    'Container(ML_Motor,"")
    'Container(Data_Acq,"", "ECMWF SAPP Module?")
    'ContainerDb(Atlas,"Metadatacatalog API with reference to annotated meteorologigcal data","Semantic database")
    'Container(GeoWeb"Visualizing WeaMyL-output in maps","GeoWeb")
    'Container(Forecaster_Backend,"Draw polygons from indicated areas from the MachineLearning output","?" )
    'Rel(geoweb, Forecaster_Backend,"MapLayers", "wms and text")
    'Rel(Forecaster,Atlas)
    'Rel(Forecaster, GeoWeb)
    




System_Ext(Thredds_rad,"Thredds_NOR", "Met Norway's Data distribution service for Satellite data","EUMETSAT")
 
System_Ext(Thredds_sat,"Thredds_NOR",  "Met Norway's Data distribution service for Radar data")
 
System_Ext(nws,"National warning  system", "The forecasters forecast working desktop tool")
 
System_Ext(Mltp,"Training platform ", "The platform for developing ML algorithms and facilities for training")

Rel_R(user_F,WeaMyL,nws,"Checking the severe weather warning proposal")
Rel_R(user_R,WeaMyL,"Getting interesting stuff from the Anotation atlas")
Rel_R(user_R,Mltp,"Training the machinlearning algorithm")
Rel_R(user_F,WeaMyL,"Editing threashold values")
Rel_R(user_SA,WeaMyL,"Unknown")

Rel_U(Thredds_rad,WeaMyL,"Getting radar data","NetCDF")
Rel_U(Thredds_sat,WeaMyL,"Getting satellite data","NetCDF")
Rel_L(WeaMyL,nws,"Suggest severe weather polygons and warning message")
Rel_U(Mltp,WeaMyL,"Deploying ML algorithm")
 
@enduml
